# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nocontrol', models.IntegerField()),
                ('Nombrealum', models.CharField(max_length=30)),
                ('Appalum', models.CharField(max_length=30)),
                ('Apmalum', models.CharField(max_length=30)),
                ('Caralum', models.CharField(max_length=30)),
                ('Semalum', models.IntegerField()),
                ('FotoAlum', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FecReg', models.DateTimeField(auto_now=True)),
                ('nocontrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Becarios')),
            ],
        ),
    ]
