# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.IntegerField()),
                ('Edad', models.IntegerField()),
            ],
        ),
    ]
