# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_delete_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becarios',
            name='FotoAlum',
        ),
        migrations.AlterField(
            model_name='registro',
            name='FecReg',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
