# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20171130_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='FechaReg',
            field=models.DateField(default=datetime.datetime(2017, 11, 30, 6, 59, 14, 703311)),
        ),
        migrations.AddField(
            model_name='registro',
            name='HoraRef',
            field=models.TimeField(default=datetime.datetime(2017, 11, 30, 6, 59, 14, 703414)),
        ),
    ]
